name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: amd64
            goarch: amd64
          - arch: arm64
            goarch: arm64
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      
      - name: Build binary
        env:
          GOOS: linux
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          go build -ldflags="-s -w -X main.version=${{ github.ref_name }}" \
            -o repoxy-linux-${{ matrix.arch }} \
            ./cmd/repoxy
      
      - name: Create checksum
        run: |
          sha256sum repoxy-linux-${{ matrix.arch }} > repoxy-linux-${{ matrix.arch }}.sha256
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: repoxy-linux-${{ matrix.arch }}
          path: |
            repoxy-linux-${{ matrix.arch }}
            repoxy-linux-${{ matrix.arch }}.sha256

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/repoxy-linux-amd64/repoxy-linux-amd64
            artifacts/repoxy-linux-amd64/repoxy-linux-amd64.sha256
            artifacts/repoxy-linux-arm64/repoxy-linux-arm64
            artifacts/repoxy-linux-arm64/repoxy-linux-arm64.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
